arch:
  - amd64
os: windows

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/build-graalvm-amd64-win64:latest -t moussavdb/build-graalvm-amd64-win64:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-graalvm-amd64-win64
  
after_success:
  - docker login -u="moussavdb" -p="test";
    docker push moussavdb/build-graalvm-amd64-win64:latest;
    docker push moussavdb/build-graalvm-amd64-win64:build_$TRAVIS_BUILD_NUMBER;
